services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: verdiant
      POSTGRES_PASSWORD: verdiant
      POSTGRES_DB: verdiant
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U verdiant -d verdiant"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data
    networks: [appnet]

  api:
    build: ../backend
    env_file:
      - ../backend/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks: [appnet]

volumes:
  db_data: {}

networks:
  appnet: {}
