name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: verdiant
          POSTGRES_PASSWORD: verdiant
          POSTGRES_DB: verdiant
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd="pg_isready -U verdiant"
          --health-interval=5s --health-timeout=5s --health-retries=20

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest httpx anyio ruff

      - name: DB migrate
        working-directory: backend
        env:
          DATABASE_URL: postgresql+asyncpg://verdiant:verdiant@localhost:5432/verdiant
        run: |
          alembic upgrade head

      - name: Run ruff
        run: ruff check backend

      - name: Run tests
        env:
          DATABASE_URL: postgresql+asyncpg://verdiant:verdiant@localhost:5432/verdiant
        run: pytest -q
